spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cartdb
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084 # Port for Cart-Service